blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # calls the post_list view when there is no optional parameter
    path('', views.post_list, name='post_list'),
   
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
     # calls the post_list view but when there is an optional param
    # slug: is a slug path converter that converts string to lowecase letters or nums with strings and underscores
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# always remember that since these variables are directly in the class and not the init constructor they are class variables


class PublishedManager(models.Manager):
    """A PublishedManager manager model class to handle all published queries"""

    def get_queryset(self):
        return super().get_queryset().filter(status='published')
        # or return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    # the slug is a field intended to be used in URLs.
    # To build beautiful and awesome SEO-friendly URLs for the blog posts
    # The URLs are built using the unique_for_date parameter which build URLs using
    # their publish date and slug
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # models.CASCADE field shows that when referenced model(in this case User) is deleted, the related blog posts of the 
    # referenced User should also be deleted
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        # the negative prefix specifies a descending order
        # Posts published recently will appear first
        ordering = ('-publish',)  # have to bring the comma after this else a model.E014 error appears where 'ordering'
        # must be a tuple or a list even if you want to order by one field

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """It is a Django convention to add a get_absolute_url method to the model that returns the
        canonical URL(in this case the Post model)"""

        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    # managers of Post
    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager
    tags = TaggableManager() # tag manager


class Comment(models.Model):
    """A comment system in a many-to-one relationship with a single Post instance"""
    # related_name attribute allows the renaming of the attribute used for relation back to the related object
    # if using the DB API now, instead of Post.comment_set.all() to retrive objects,
    # it can be Post.comments.all
    # so by default if you don't set the related_name, Django will create a lowercase of the model with _set added
    # to name the manager of the related object like seen in Post.comment_set.all()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # this will be used to deactivate inappropriate comments
    active = models.BooleanField(default=True)


    class Meta:
        # always remember: class Meta makes you select which field to post your model by.
        # comments will be posted based on time of creation
        ordering = ('created',)


    def __str__(self):
        return f'Comment by {self.name} on {self.post}'




    
    








# Create your models here

blog/forms.py
from django import forms
from .models import Comment


# Django has two Form base classes, forms.Form and forms.ModelForm
# forms.Form are to create independent form models
# forms.ModelForm are to create forms dynamically from other classes in model.py

class EmailPostForm(forms.Form):
    """A form to send emails of posts"""
    # forms.CharField is rendered as <input type="text"> HTML element.
    # every form field has a default widget.
    name = forms.CharField(max_length=25)
    # if an email isn't typed in this field an forms.ValidationError will occur 
    # and form will not validate
    email = forms.EmailField()
    to = forms.EmailField()
    # we overrided comments CharField form to rather be a like a TextArea
    # we make comments field optional by making required=False
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """A  dynamic form to handle comments of blog posts"""

    class Meta:
        # to create a form from the model, you indicate the model you want to use in the class Meta
        # by default Django uses all the model fields for the Form fields unless you explictly define
        # the fields list attribute shows which fields to add,
        # an exclude attribute shows the lists of fields to exclude from the CommentForm fields
        model = Comment
        fields = ('name', 'email', 'body')



    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


def post_list(request, tag_slug=None):
    """How the post_list view works.
    - Take an optional slug parameter that has a default of None but if there is will be in the URL.
    - All published posts will be retrieved and if a published post has a tag/tags, the Tag object,
     is retrieved.
     -Posts are then filtered by the ones that have tags"""

    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        # filter through the list of posts for the post instances that have the given tag/tags
        object_list = object_list.filter(tags__in=[tag])


    # we are paginating the post list using a Paginator class to make sure only 3 posts appear 
    # on the post list page at a time
    paginator = Paginator(object_list, 3) 
    page = request.GET.get('page') # this indicates the current page number
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer return the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver the last page of results
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'page': page,
        'tag': tag,
        }

    return render(request, 'blog/post/list.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    # to retrieve active comments of the post instance
    comments = post.comments.filter(active=True)  # remember it is post.comments.filter because of the related_name attribute
    # in the post field of Comment model

    # also give our users opportunity to add new comments
    # defining a new_comment variable and making it empty by assigning to None
    new_comment = None


    # CommentForms will be handled in the post_detail view 
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create Comment but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # then assign the current post to the comment
            new_comment.post = post
            # now save
            new_comment.save()
        else:
            comment_form = CommentForm()

            # note to self: save() method is available for ModelForm instances and not Form instances because
            # they are not linked to any models

    # recommending posts to user based on similarity of tags. In order to do this:
    # - returning all tags of the particular post instance
    # - get all the other posts that have any of those tags
    # - exclude the current post from the list of posts you will recommend as having similar tags
    # - the greater the number of tags shared between one post and the subject post, the greater the similarity
    # - if posts share the same number of tags choose the most recent one
    # - we limit the query to the number of posts we want to recommend


    #the values_list returns a tuple for a given field
    # convert the tags id's of the post instance into a list with flat=True because tuples are not iterables.
    post_tags_id = post.tags.values_list('id', flat=True)
    # use the post id's to search for other posts that share same tag but the particular post itself
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    # count the number of tags using the Count aggregation method, then order
    # for the posts with more tags and if share same tags for most recently published
    # negative prefix denotes descending order
    # only first 4 posts retrieved are recommended
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]



    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'comment_form': commment_form,
        'new_comment': new_comment,
        'similar_posts': similar_posts,
    })


def post_share(request, post_id):
    # retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    # after retrieving 
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            # cleaned_data acts like a dictionary that stores the validated fields
            cd = form.cleaned_data
            # send email
            # build a complete URL including HTTP schema and hostname using request.build_absolute_url with post.get_absolute_url
            # as path 
            post_url = request.build_absolute_url(post.get_absolute_url())
            subject = f"{cd['name']} {cd['email']} recommends you reading {post.title}"
            message = f"Read {post.title} at {post_url} \n{cd['name']}'s comments: {cd['comments']}"
            # [cd['to']] is a list because send_mail function takes the receipients as a list
            send_mail(subject, message, 'gabdanq@gmail.com', [cd['to']]) 
            sent = True
    else:
        # if no request post method return a new form instance 
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {
        'post': post,
        'form': form,
        'sent': sent,
    })

# Create your views here.


# class based listview commented out
"""class PostListView(ListView):
    # since i defined the model manager in models.py to retrive only published posts,
    # there is no need for me to create a def get_queryset() class method like i did in the polls app,
    # and can just use a queryset attribute to link to my model manager to do the filtering
    # i think this decouples my code too. Sweet!!

    # also because we were retrieving a particular set of objects,
    # we didn't use the generic attibute model = Post which would have rather fetched,
    # model = Post which is equal to Post.objects.all() queryset
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'"""

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

<!-- another thing to note. Since we want the detail of each post, -->
<!-- there is no need to iterate over the items in Post because -->
<!-- the detail URL is a slug for one particular post and not series of posts -->
{% block title %} {{post.title}} {% endblock %}

{% block content %}
<h1>{{post.title}}</h1>
<p class="date">
    Published {{posts.publish}} by {{post.author}}
</p>
{{post.body|linebreaks}}
<p>
    <!-- this is a dynamic url remember that way you don't hardcode the actual url of post_share in the template -->
    <!-- therefore any change in the url is made in the urls.py urlpatterns variable -->
    <a href="{% url "blog:post_share" post.id %}">
        Share this post
    </a>
</p>

<!-- displaying similar posts to the post instance -->
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{% post.get_absolute_url %}">{{post.title}}</a>
</p>
{% empty %}
There are no similar posts yet
{% endfor %}

<!-- displaying list of comments -->

<!-- {% with %} tag acts just like a normal Python context manager and assigns comments.count method to a variable,-->
<!-- that will be available until the {% endwith %} tag -->
{% with comments.count as total_comments %}
<h2>
    <!-- pluralize suffix adds a plural suffix or string 's' to the word comment depending on the value of total comments  -->
    <!-- so if value of total_comments is 1, then comment but for 0 or > 1, comments -->
        {{total_comments}}comment{{total_comments|pluralize}} 
</h2>
<!-- instead of straight away beginning with the for comment in comments loop, -->
<!-- could do an if comments tag then instead of the empty tag we use an else statement tag -->
{% for comment in comments %}
<div class="comments">
    <p class="info">
        <!-- forloop.counter counts the value for each iteration -->
        Comment {{forloop.counter}} by {{comment.name}}
        {{comment.created}}
    </p>
    {{comment.body|linebreaks}}
</div>
<!-- default message if comments list is empty -->
{% empty %}
<p>There are no comments yet</p>

<!-- rendering the comment form -->
{% if new_comment %}
<h2>Your comment has been added</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="." method="POST">
    <!-- render comment_form as paragraph -->
    {{comment_form.as_p}}
    {% csrf_token %}
    <p><input type="submit" value="Add comment here"></p>
</form>
{% endif %}
 
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}

{% block content %}
<!-- if a tag link is clicked on, then this is returned -->
<!-- but if not then the normal list of  published posts are returned -->
{% if tag %}
<h2>Posts tagged with "{{tag.name}}"</h2>
{% endif %}

{% for post in posts %}
<!-- so there are two URL's here. There is the post.get_absolute_url for the detail of the posts -->
<!-- then there is a URL for the tags so the user can find posts with same tags -->
<h2>
    <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
</h2>
<p class="tags">
    <!-- adding tags of posts and a custom link to their URL -->
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{tag.name}}</a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
    
<p class="date">
    Published {{post.publish}} by {{post.author}}
</p>
{{post.body|truncatewords:30|linebreaks}}
{% endfor %}
<!-- linking the pagination.html to the body content tag so the lists, -->
<!-- of published blog posts appear in paginated form -->
<!-- Also since the page object we are passing to the list template is called posts, -->
<!-- in django class generic views, the selected page would have been a variable called page_obj-->
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
<!-- this is the template that handles email forms -->
{% extends 'blog/base.html' %} 

{% block title %} Share a post {% endblock %}

{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{post.title}}" was successfully sent to {{form.cleaned_data.to}}
</p>
{% else %}
<h1>Share "{{post.title}} by e-mail</h1>
<form action="." method="POST">
    <!-- we render each field in the form instance(EmailPostForm()) as a paragraph with as_p method -->
    <!-- To render as an unordered list, use as_ul and to render as HTML table, use as_table method  -->
    <!-- we could also use a for loop to iterate through all the fields in form -->
    {{form.as_p}}
    <!-- every form with a POST method needs a csrf token to avoid cross site forgeries -->
    {% csrf_token %} 
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}